-- `municipios`: el nomenclátor oficial de Cataluña, y la primera clave para hablar de
-- territorio sin adivinar.
--
-- EL PROBLEMA. Hoy el municipio es **texto libre** en tres sitios distintos:
-- `productores.poblacion`, `productores.area_geografica` y
-- `productor_ubicaciones.municipio`. La priorización de entidades (§6ter) puntúa «mismo
-- municipio +2» comparando cadenas, así que «Sant Cugat del Vallès», «Sant Cugat» y
-- «SANT CUGAT» son tres municipios distintos; y el albarán de entrega (D3 del plan) tiene
-- que decir el municipio y la **comarca** de origen sin nombrar al donante, cosa que con
-- texto libre no se puede resolver.
--
-- QUÉ SE SIEMBRA. Los **947 municipios** de Cataluña con su código INE de 5 dígitos, su
-- nombre oficial en catalán, su comarca y su provincia. Es dato público (IDESCAT y el
-- Institut Nacional d'Estadística), no lleva ni un dato personal, y por eso sí puede
-- vivir en git —al revés que los CSV de `scripts/data/` (§7)—.
--
-- PROCEDENCIA, para poder rehacerlo:
--   · nombres y códigos: `https://api.idescat.cat/emex/v1/nodes.json?tipus=mun&lang=ca`
--     (id de 6 cifras = INE de 5 + dígito de control; aquí se guardan las 5 primeras).
--   · comarca: dataset «Municipis Catalunya Geo» del portal de dades obertes de la
--     Generalitat (`analisi.transparenciacatalunya.cat`, recurso `9aju-tpwc`).
--   Los 947 códigos de las dos fuentes coinciden exactamente, y los 947 nombres también:
--   no hay ninguna fila reconciliada a mano ni ningún código compuesto por nadie.
--
-- Incluye las **43 comarcas** vigentes, el Moianès (2015) y el Lluçanès (2023) incluidos.
--
-- EL NOMBRE LLEVA EL ARTÍCULO POSPUESTO, que es la forma oficial del nomenclátor:
-- `Ametlla del Vallès, l'`, `Canonja, la`, `Espluga de Francolí, l'`. Se guarda tal cual
-- —es la forma que ordena bien alfabéticamente y la que usan los registros oficiales—;
-- si algún día hace falta pintarlo natural («l'Ametlla del Vallès»), es cosa de la
-- interfaz, no del dato.
--
-- LA COLUMNA `municipio_ine` NACE NULA EN LAS 12 UBICACIONES QUE HAY. El casado por
-- nombre de lo que ya está escrito a mano es un script aparte y una decisión con
-- ambigüedades reales (hay nombres repetidos entre provincias); esta migración solo
-- pone el catálogo y el sitio donde apuntar.

-- ---------------------------------------------------------------------------
-- 1. El catálogo
-- ---------------------------------------------------------------------------
create table if not exists municipios (
  -- Código INE de 5 dígitos: 2 de provincia + 3 de municipio. Es texto y no int porque
  -- los de Barcelona empiezan por 0 y un entero se los comería.
  codi_ine  text primary key check (codi_ine ~ '^[0-9]{5}$'),
  nom       text not null,
  comarca   text not null,
  provincia text not null check (provincia in ('Barcelona', 'Girona', 'Lleida', 'Tarragona'))
);

comment on table municipios is
  'Nomenclátor oficial de Cataluña (947 municipios, 43 comarcas). Dato público de IDESCAT: sí va en git.';
comment on column municipios.nom is
  'Nombre oficial en catalán, con el artículo pospuesto: «Ametlla del Vallès, l''».';

-- Los dos accesos que hace la interfaz: buscar por nombre y agrupar por comarca.
create index if not exists municipios_nom_idx     on municipios (nom);
create index if not exists municipios_comarca_idx on municipios (comarca);

-- ---------------------------------------------------------------------------
-- 2. La ubicación de un productor puede apuntar al catálogo
-- ---------------------------------------------------------------------------
-- Nullable, y el `municipio` de texto libre se queda donde está: es lo que hay escrito
-- hoy y lo que sigue leyendo el intake. La columna nueva es la que van a usar la
-- priorización y el albarán cuando el casado exista.
alter table productor_ubicaciones
  add column if not exists municipio_ine text references municipios(codi_ine);

create index if not exists productor_ubicaciones_municipio_ine_idx
  on productor_ubicaciones (municipio_ine);

comment on column productor_ubicaciones.municipio_ine is
  'Municipio del catálogo. Nulo mientras no se case con el texto libre de `municipio` (script aparte).';

-- ---------------------------------------------------------------------------
-- 3. Seed: los 947
-- ---------------------------------------------------------------------------
-- `do update` para que reaplicarlo corrija nombres o comarcas (el Lluçanès movió
-- municipios que antes eran de Osona y del Berguedà) sin duplicar nada.
insert into municipios (codi_ine, nom, comarca, provincia) values
  ('08001', 'Abrera', 'Baix Llobregat', 'Barcelona'),
  ('08002', 'Aguilar de Segarra', 'Bages', 'Barcelona'),
  ('08003', 'Alella', 'Maresme', 'Barcelona'),
  ('08004', 'Alpens', 'Lluçanès', 'Barcelona'),
  ('08005', 'Ametlla del Vallès, l''', 'Vallès Oriental', 'Barcelona'),
  ('08006', 'Arenys de Mar', 'Maresme', 'Barcelona'),
  ('08007', 'Arenys de Munt', 'Maresme', 'Barcelona'),
  ('08008', 'Argençola', 'Anoia', 'Barcelona'),
  ('08009', 'Argentona', 'Maresme', 'Barcelona'),
  ('08010', 'Artés', 'Bages', 'Barcelona'),
  ('08011', 'Avià', 'Berguedà', 'Barcelona'),
  ('08012', 'Avinyó', 'Bages', 'Barcelona'),
  ('08013', 'Avinyonet del Penedès', 'Alt Penedès', 'Barcelona'),
  ('08014', 'Aiguafreda', 'Osona', 'Barcelona'),
  ('08015', 'Badalona', 'Barcelonès', 'Barcelona'),
  ('08016', 'Bagà', 'Berguedà', 'Barcelona'),
  ('08017', 'Balenyà', 'Osona', 'Barcelona'),
  ('08018', 'Balsareny', 'Bages', 'Barcelona'),
  ('08019', 'Barcelona', 'Barcelonès', 'Barcelona'),
  ('08020', 'Begues', 'Baix Llobregat', 'Barcelona'),
  ('08021', 'Bellprat', 'Anoia', 'Barcelona'),
  ('08022', 'Berga', 'Berguedà', 'Barcelona'),
  ('08023', 'Bigues i Riells del Fai', 'Vallès Oriental', 'Barcelona'),
  ('08024', 'Borredà', 'Berguedà', 'Barcelona'),
  ('08025', 'Bruc, el', 'Anoia', 'Barcelona'),
  ('08026', 'Brull, el', 'Osona', 'Barcelona'),
  ('08027', 'Cabanyes, les', 'Alt Penedès', 'Barcelona'),
  ('08028', 'Cabrera d''Anoia', 'Anoia', 'Barcelona'),
  ('08029', 'Cabrera de Mar', 'Maresme', 'Barcelona'),
  ('08030', 'Cabrils', 'Maresme', 'Barcelona'),
  ('08031', 'Calaf', 'Anoia', 'Barcelona'),
  ('08032', 'Caldes d''Estrac', 'Maresme', 'Barcelona'),
  ('08033', 'Caldes de Montbui', 'Vallès Oriental', 'Barcelona'),
  ('08034', 'Calders', 'Moianès', 'Barcelona'),
  ('08035', 'Calella', 'Maresme', 'Barcelona'),
  ('08036', 'Calonge de Segarra', 'Anoia', 'Barcelona'),
  ('08037', 'Calldetenes', 'Osona', 'Barcelona'),
  ('08038', 'Callús', 'Bages', 'Barcelona'),
  ('08039', 'Campins', 'Vallès Oriental', 'Barcelona'),
  ('08040', 'Canet de Mar', 'Maresme', 'Barcelona'),
  ('08041', 'Canovelles', 'Vallès Oriental', 'Barcelona'),
  ('08042', 'Cànoves i Samalús', 'Vallès Oriental', 'Barcelona'),
  ('08043', 'Canyelles', 'Garraf', 'Barcelona'),
  ('08044', 'Capellades', 'Anoia', 'Barcelona'),
  ('08045', 'Capolat', 'Berguedà', 'Barcelona'),
  ('08046', 'Cardedeu', 'Vallès Oriental', 'Barcelona'),
  ('08047', 'Cardona', 'Bages', 'Barcelona'),
  ('08048', 'Carme', 'Anoia', 'Barcelona'),
  ('08049', 'Casserres', 'Berguedà', 'Barcelona'),
  ('08050', 'Castellar del Riu', 'Berguedà', 'Barcelona'),
  ('08051', 'Castellar del Vallès', 'Vallès Occidental', 'Barcelona'),
  ('08052', 'Castellar de n''Hug', 'Berguedà', 'Barcelona'),
  ('08053', 'Castellbell i el Vilar', 'Bages', 'Barcelona'),
  ('08054', 'Castellbisbal', 'Vallès Occidental', 'Barcelona'),
  ('08055', 'Castellcir', 'Moianès', 'Barcelona'),
  ('08056', 'Castelldefels', 'Baix Llobregat', 'Barcelona'),
  ('08057', 'Castell de l''Areny', 'Berguedà', 'Barcelona'),
  ('08058', 'Castellet i la Gornal', 'Alt Penedès', 'Barcelona'),
  ('08059', 'Castellfollit del Boix', 'Bages', 'Barcelona'),
  ('08060', 'Castellfollit de Riubregós', 'Anoia', 'Barcelona'),
  ('08061', 'Castellgalí', 'Bages', 'Barcelona'),
  ('08062', 'Castellnou de Bages', 'Bages', 'Barcelona'),
  ('08063', 'Castellolí', 'Anoia', 'Barcelona'),
  ('08064', 'Castellterçol', 'Moianès', 'Barcelona'),
  ('08065', 'Castellví de la Marca', 'Alt Penedès', 'Barcelona'),
  ('08066', 'Castellví de Rosanes', 'Baix Llobregat', 'Barcelona'),
  ('08067', 'Centelles', 'Osona', 'Barcelona'),
  ('08068', 'Cervelló', 'Baix Llobregat', 'Barcelona'),
  ('08069', 'Collbató', 'Baix Llobregat', 'Barcelona'),
  ('08070', 'Collsuspina', 'Moianès', 'Barcelona'),
  ('08071', 'Copons', 'Anoia', 'Barcelona'),
  ('08072', 'Corbera de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08073', 'Cornellà de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08074', 'Cubelles', 'Garraf', 'Barcelona'),
  ('08075', 'Dosrius', 'Maresme', 'Barcelona'),
  ('08076', 'Esparreguera', 'Baix Llobregat', 'Barcelona'),
  ('08077', 'Esplugues de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08078', 'Espunyola, l''', 'Berguedà', 'Barcelona'),
  ('08079', 'Estany, l''', 'Moianès', 'Barcelona'),
  ('08080', 'Fígols', 'Berguedà', 'Barcelona'),
  ('08081', 'Fogars de Montclús', 'Vallès Oriental', 'Barcelona'),
  ('08082', 'Fogars de la Selva', 'Selva', 'Barcelona'),
  ('08083', 'Folgueroles', 'Osona', 'Barcelona'),
  ('08084', 'Fonollosa', 'Bages', 'Barcelona'),
  ('08085', 'Font-rubí', 'Alt Penedès', 'Barcelona'),
  ('08086', 'Franqueses del Vallès, les', 'Vallès Oriental', 'Barcelona'),
  ('08087', 'Gallifa', 'Vallès Occidental', 'Barcelona'),
  ('08088', 'Garriga, la', 'Vallès Oriental', 'Barcelona'),
  ('08089', 'Gavà', 'Baix Llobregat', 'Barcelona'),
  ('08090', 'Gaià', 'Bages', 'Barcelona'),
  ('08091', 'Gelida', 'Alt Penedès', 'Barcelona'),
  ('08092', 'Gironella', 'Berguedà', 'Barcelona'),
  ('08093', 'Gisclareny', 'Berguedà', 'Barcelona'),
  ('08094', 'Granada, la', 'Alt Penedès', 'Barcelona'),
  ('08095', 'Granera', 'Moianès', 'Barcelona'),
  ('08096', 'Granollers', 'Vallès Oriental', 'Barcelona'),
  ('08097', 'Gualba', 'Vallès Oriental', 'Barcelona'),
  ('08098', 'Sant Salvador de Guardiola', 'Bages', 'Barcelona'),
  ('08099', 'Guardiola de Berguedà', 'Berguedà', 'Barcelona'),
  ('08100', 'Gurb', 'Osona', 'Barcelona'),
  ('08101', 'Hospitalet de Llobregat, l''', 'Barcelonès', 'Barcelona'),
  ('08102', 'Igualada', 'Anoia', 'Barcelona'),
  ('08103', 'Jorba', 'Anoia', 'Barcelona'),
  ('08104', 'Llacuna, la', 'Anoia', 'Barcelona'),
  ('08105', 'Llagosta, la', 'Vallès Oriental', 'Barcelona'),
  ('08106', 'Llinars del Vallès', 'Vallès Oriental', 'Barcelona'),
  ('08107', 'Lliçà d''Amunt', 'Vallès Oriental', 'Barcelona'),
  ('08108', 'Lliçà de Vall', 'Vallès Oriental', 'Barcelona'),
  ('08109', 'Lluçà', 'Lluçanès', 'Barcelona'),
  ('08110', 'Malgrat de Mar', 'Maresme', 'Barcelona'),
  ('08111', 'Malla', 'Osona', 'Barcelona'),
  ('08112', 'Manlleu', 'Osona', 'Barcelona'),
  ('08113', 'Manresa', 'Bages', 'Barcelona'),
  ('08114', 'Martorell', 'Baix Llobregat', 'Barcelona'),
  ('08115', 'Martorelles', 'Vallès Oriental', 'Barcelona'),
  ('08116', 'Masies de Roda, les', 'Osona', 'Barcelona'),
  ('08117', 'Masies de Voltregà, les', 'Osona', 'Barcelona'),
  ('08118', 'Masnou, el', 'Maresme', 'Barcelona'),
  ('08119', 'Masquefa', 'Anoia', 'Barcelona'),
  ('08120', 'Matadepera', 'Vallès Occidental', 'Barcelona'),
  ('08121', 'Mataró', 'Maresme', 'Barcelona'),
  ('08122', 'Mediona', 'Alt Penedès', 'Barcelona'),
  ('08123', 'Molins de Rei', 'Baix Llobregat', 'Barcelona'),
  ('08124', 'Mollet del Vallès', 'Vallès Oriental', 'Barcelona'),
  ('08125', 'Montcada i Reixac', 'Vallès Occidental', 'Barcelona'),
  ('08126', 'Montgat', 'Maresme', 'Barcelona'),
  ('08127', 'Monistrol de Montserrat', 'Bages', 'Barcelona'),
  ('08128', 'Monistrol de Calders', 'Moianès', 'Barcelona'),
  ('08129', 'Muntanyola', 'Osona', 'Barcelona'),
  ('08130', 'Montclar', 'Berguedà', 'Barcelona'),
  ('08131', 'Montesquiu', 'Osona', 'Barcelona'),
  ('08132', 'Montmajor', 'Berguedà', 'Barcelona'),
  ('08133', 'Montmaneu', 'Anoia', 'Barcelona'),
  ('08134', 'Figaró-Montmany', 'Vallès Oriental', 'Barcelona'),
  ('08135', 'Montmeló', 'Vallès Oriental', 'Barcelona'),
  ('08136', 'Montornès del Vallès', 'Vallès Oriental', 'Barcelona'),
  ('08137', 'Montseny', 'Vallès Oriental', 'Barcelona'),
  ('08138', 'Moià', 'Moianès', 'Barcelona'),
  ('08139', 'Mura', 'Bages', 'Barcelona'),
  ('08140', 'Navarcles', 'Bages', 'Barcelona'),
  ('08141', 'Navàs', 'Bages', 'Barcelona'),
  ('08142', 'Nou de Berguedà, la', 'Berguedà', 'Barcelona'),
  ('08143', 'Òdena', 'Anoia', 'Barcelona'),
  ('08144', 'Olvan', 'Berguedà', 'Barcelona'),
  ('08145', 'Olèrdola', 'Alt Penedès', 'Barcelona'),
  ('08146', 'Olesa de Bonesvalls', 'Alt Penedès', 'Barcelona'),
  ('08147', 'Olesa de Montserrat', 'Baix Llobregat', 'Barcelona'),
  ('08148', 'Olivella', 'Garraf', 'Barcelona'),
  ('08149', 'Olost', 'Lluçanès', 'Barcelona'),
  ('08150', 'Orís', 'Osona', 'Barcelona'),
  ('08151', 'Oristà', 'Lluçanès', 'Barcelona'),
  ('08152', 'Orpí', 'Anoia', 'Barcelona'),
  ('08153', 'Òrrius', 'Maresme', 'Barcelona'),
  ('08154', 'Pacs del Penedès', 'Alt Penedès', 'Barcelona'),
  ('08155', 'Palafolls', 'Maresme', 'Barcelona'),
  ('08156', 'Palau-solità i Plegamans', 'Vallès Occidental', 'Barcelona'),
  ('08157', 'Pallejà', 'Baix Llobregat', 'Barcelona'),
  ('08158', 'Papiol, el', 'Baix Llobregat', 'Barcelona'),
  ('08159', 'Parets del Vallès', 'Vallès Oriental', 'Barcelona'),
  ('08160', 'Perafita', 'Lluçanès', 'Barcelona'),
  ('08161', 'Piera', 'Anoia', 'Barcelona'),
  ('08162', 'Hostalets de Pierola, els', 'Anoia', 'Barcelona'),
  ('08163', 'Pineda de Mar', 'Maresme', 'Barcelona'),
  ('08164', 'Pla del Penedès, el', 'Alt Penedès', 'Barcelona'),
  ('08165', 'Pobla de Claramunt, la', 'Anoia', 'Barcelona'),
  ('08166', 'Pobla de Lillet, la', 'Berguedà', 'Barcelona'),
  ('08167', 'Polinyà', 'Vallès Occidental', 'Barcelona'),
  ('08168', 'Pontons', 'Alt Penedès', 'Barcelona'),
  ('08169', 'Prat de Llobregat, el', 'Baix Llobregat', 'Barcelona'),
  ('08170', 'Prats de Rei, els', 'Anoia', 'Barcelona'),
  ('08171', 'Prats de Lluçanès', 'Lluçanès', 'Barcelona'),
  ('08172', 'Premià de Mar', 'Maresme', 'Barcelona'),
  ('08174', 'Puigdàlber', 'Alt Penedès', 'Barcelona'),
  ('08175', 'Puig-reig', 'Berguedà', 'Barcelona'),
  ('08176', 'Pujalt', 'Anoia', 'Barcelona'),
  ('08177', 'Quar, la', 'Berguedà', 'Barcelona'),
  ('08178', 'Rajadell', 'Bages', 'Barcelona'),
  ('08179', 'Rellinars', 'Vallès Occidental', 'Barcelona'),
  ('08180', 'Ripollet', 'Vallès Occidental', 'Barcelona'),
  ('08181', 'Roca del Vallès, la', 'Vallès Oriental', 'Barcelona'),
  ('08182', 'Pont de Vilomara i Rocafort, el', 'Bages', 'Barcelona'),
  ('08183', 'Roda de Ter', 'Osona', 'Barcelona'),
  ('08184', 'Rubí', 'Vallès Occidental', 'Barcelona'),
  ('08185', 'Rubió', 'Anoia', 'Barcelona'),
  ('08187', 'Sabadell', 'Vallès Occidental', 'Barcelona'),
  ('08188', 'Sagàs', 'Berguedà', 'Barcelona'),
  ('08189', 'Sant Pere Sallavinera', 'Anoia', 'Barcelona'),
  ('08190', 'Saldes', 'Berguedà', 'Barcelona'),
  ('08191', 'Sallent', 'Bages', 'Barcelona'),
  ('08192', 'Santpedor', 'Bages', 'Barcelona'),
  ('08193', 'Sant Iscle de Vallalta', 'Maresme', 'Barcelona'),
  ('08194', 'Sant Adrià de Besòs', 'Barcelonès', 'Barcelona'),
  ('08195', 'Sant Agustí de Lluçanès', 'Osona', 'Barcelona'),
  ('08196', 'Sant Andreu de la Barca', 'Baix Llobregat', 'Barcelona'),
  ('08197', 'Sant Andreu de Llavaneres', 'Maresme', 'Barcelona'),
  ('08198', 'Sant Antoni de Vilamajor', 'Vallès Oriental', 'Barcelona'),
  ('08199', 'Sant Bartomeu del Grau', 'Osona', 'Barcelona'),
  ('08200', 'Sant Boi de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08201', 'Sant Boi de Lluçanès', 'Osona', 'Barcelona'),
  ('08202', 'Sant Celoni', 'Vallès Oriental', 'Barcelona'),
  ('08203', 'Sant Cebrià de Vallalta', 'Maresme', 'Barcelona'),
  ('08204', 'Sant Climent de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08205', 'Sant Cugat del Vallès', 'Vallès Occidental', 'Barcelona'),
  ('08206', 'Sant Cugat Sesgarrigues', 'Alt Penedès', 'Barcelona'),
  ('08207', 'Sant Esteve de Palautordera', 'Vallès Oriental', 'Barcelona'),
  ('08208', 'Sant Esteve Sesrovires', 'Baix Llobregat', 'Barcelona'),
  ('08209', 'Sant Fost de Campsentelles', 'Vallès Oriental', 'Barcelona'),
  ('08210', 'Sant Feliu de Codines', 'Vallès Oriental', 'Barcelona'),
  ('08211', 'Sant Feliu de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08212', 'Sant Feliu Sasserra', 'Bages', 'Barcelona'),
  ('08213', 'Sant Fruitós de Bages', 'Bages', 'Barcelona'),
  ('08214', 'Vilassar de Dalt', 'Maresme', 'Barcelona'),
  ('08215', 'Sant Hipòlit de Voltregà', 'Osona', 'Barcelona'),
  ('08216', 'Sant Jaume de Frontanyà', 'Berguedà', 'Barcelona'),
  ('08217', 'Sant Joan Despí', 'Baix Llobregat', 'Barcelona'),
  ('08218', 'Sant Joan de Vilatorrada', 'Bages', 'Barcelona'),
  ('08219', 'Vilassar de Mar', 'Maresme', 'Barcelona'),
  ('08220', 'Sant Julià de Vilatorta', 'Osona', 'Barcelona'),
  ('08221', 'Sant Just Desvern', 'Baix Llobregat', 'Barcelona'),
  ('08222', 'Sant Llorenç d''Hortons', 'Alt Penedès', 'Barcelona'),
  ('08223', 'Sant Llorenç Savall', 'Vallès Occidental', 'Barcelona'),
  ('08224', 'Sant Martí de Centelles', 'Osona', 'Barcelona'),
  ('08225', 'Sant Martí d''Albars', 'Lluçanès', 'Barcelona'),
  ('08226', 'Sant Martí de Tous', 'Anoia', 'Barcelona'),
  ('08227', 'Sant Martí Sarroca', 'Alt Penedès', 'Barcelona'),
  ('08228', 'Sant Martí Sesgueioles', 'Anoia', 'Barcelona'),
  ('08229', 'Sant Mateu de Bages', 'Bages', 'Barcelona'),
  ('08230', 'Premià de Dalt', 'Maresme', 'Barcelona'),
  ('08231', 'Sant Pere de Ribes', 'Garraf', 'Barcelona'),
  ('08232', 'Sant Pere de Riudebitlles', 'Alt Penedès', 'Barcelona'),
  ('08233', 'Sant Pere de Torelló', 'Osona', 'Barcelona'),
  ('08234', 'Sant Pere de Vilamajor', 'Vallès Oriental', 'Barcelona'),
  ('08235', 'Sant Pol de Mar', 'Maresme', 'Barcelona'),
  ('08236', 'Sant Quintí de Mediona', 'Alt Penedès', 'Barcelona'),
  ('08237', 'Sant Quirze de Besora', 'Osona', 'Barcelona'),
  ('08238', 'Sant Quirze del Vallès', 'Vallès Occidental', 'Barcelona'),
  ('08239', 'Sant Quirze Safaja', 'Moianès', 'Barcelona'),
  ('08240', 'Sant Sadurní d''Anoia', 'Alt Penedès', 'Barcelona'),
  ('08241', 'Sant Sadurní d''Osormort', 'Osona', 'Barcelona'),
  ('08242', 'Marganell', 'Bages', 'Barcelona'),
  ('08243', 'Santa Cecília de Voltregà', 'Osona', 'Barcelona'),
  ('08244', 'Santa Coloma de Cervelló', 'Baix Llobregat', 'Barcelona'),
  ('08245', 'Santa Coloma de Gramenet', 'Barcelonès', 'Barcelona'),
  ('08246', 'Santa Eugènia de Berga', 'Osona', 'Barcelona'),
  ('08247', 'Santa Eulàlia de Riuprimer', 'Osona', 'Barcelona'),
  ('08248', 'Santa Eulàlia de Ronçana', 'Vallès Oriental', 'Barcelona'),
  ('08249', 'Santa Fe del Penedès', 'Alt Penedès', 'Barcelona'),
  ('08250', 'Santa Margarida de Montbui', 'Anoia', 'Barcelona'),
  ('08251', 'Santa Margarida i els Monjos', 'Alt Penedès', 'Barcelona'),
  ('08252', 'Barberà del Vallès', 'Vallès Occidental', 'Barcelona'),
  ('08253', 'Santa Maria de Besora', 'Osona', 'Barcelona'),
  ('08254', 'Esquirol, l''', 'Osona', 'Barcelona'),
  ('08255', 'Santa Maria de Merlès', 'Berguedà', 'Barcelona'),
  ('08256', 'Santa Maria de Martorelles', 'Vallès Oriental', 'Barcelona'),
  ('08257', 'Santa Maria de Miralles', 'Anoia', 'Barcelona'),
  ('08258', 'Santa Maria d''Oló', 'Moianès', 'Barcelona'),
  ('08259', 'Santa Maria de Palautordera', 'Vallès Oriental', 'Barcelona'),
  ('08260', 'Santa Perpètua de Mogoda', 'Vallès Occidental', 'Barcelona'),
  ('08261', 'Santa Susanna', 'Maresme', 'Barcelona'),
  ('08262', 'Sant Vicenç de Castellet', 'Bages', 'Barcelona'),
  ('08263', 'Sant Vicenç dels Horts', 'Baix Llobregat', 'Barcelona'),
  ('08264', 'Sant Vicenç de Montalt', 'Maresme', 'Barcelona'),
  ('08265', 'Sant Vicenç de Torelló', 'Osona', 'Barcelona'),
  ('08266', 'Cerdanyola del Vallès', 'Vallès Occidental', 'Barcelona'),
  ('08267', 'Sentmenat', 'Vallès Occidental', 'Barcelona'),
  ('08268', 'Cercs', 'Berguedà', 'Barcelona'),
  ('08269', 'Seva', 'Osona', 'Barcelona'),
  ('08270', 'Sitges', 'Garraf', 'Barcelona'),
  ('08271', 'Sobremunt', 'Lluçanès', 'Barcelona'),
  ('08272', 'Sora', 'Osona', 'Barcelona'),
  ('08273', 'Subirats', 'Alt Penedès', 'Barcelona'),
  ('08274', 'Súria', 'Bages', 'Barcelona'),
  ('08275', 'Tavèrnoles', 'Osona', 'Barcelona'),
  ('08276', 'Tagamanent', 'Vallès Oriental', 'Barcelona'),
  ('08277', 'Talamanca', 'Bages', 'Barcelona'),
  ('08278', 'Taradell', 'Osona', 'Barcelona'),
  ('08279', 'Terrassa', 'Vallès Occidental', 'Barcelona'),
  ('08280', 'Tavertet', 'Osona', 'Barcelona'),
  ('08281', 'Teià', 'Maresme', 'Barcelona'),
  ('08282', 'Tiana', 'Maresme', 'Barcelona'),
  ('08283', 'Tona', 'Osona', 'Barcelona'),
  ('08284', 'Tordera', 'Maresme', 'Barcelona'),
  ('08285', 'Torelló', 'Osona', 'Barcelona'),
  ('08286', 'Torre de Claramunt, la', 'Anoia', 'Barcelona'),
  ('08287', 'Torrelavit', 'Alt Penedès', 'Barcelona'),
  ('08288', 'Torrelles de Foix', 'Alt Penedès', 'Barcelona'),
  ('08289', 'Torrelles de Llobregat', 'Baix Llobregat', 'Barcelona'),
  ('08290', 'Ullastrell', 'Vallès Occidental', 'Barcelona'),
  ('08291', 'Vacarisses', 'Vallès Occidental', 'Barcelona'),
  ('08292', 'Vallbona d''Anoia', 'Anoia', 'Barcelona'),
  ('08293', 'Vallcebre', 'Berguedà', 'Barcelona'),
  ('08294', 'Vallgorguina', 'Vallès Oriental', 'Barcelona'),
  ('08295', 'Vallirana', 'Baix Llobregat', 'Barcelona'),
  ('08296', 'Vallromanes', 'Vallès Oriental', 'Barcelona'),
  ('08297', 'Veciana', 'Anoia', 'Barcelona'),
  ('08298', 'Vic', 'Osona', 'Barcelona'),
  ('08299', 'Vilada', 'Berguedà', 'Barcelona'),
  ('08300', 'Viladecavalls', 'Vallès Occidental', 'Barcelona'),
  ('08301', 'Viladecans', 'Baix Llobregat', 'Barcelona'),
  ('08302', 'Vilanova del Camí', 'Anoia', 'Barcelona'),
  ('08303', 'Vilanova de Sau', 'Osona', 'Barcelona'),
  ('08304', 'Vilobí del Penedès', 'Alt Penedès', 'Barcelona'),
  ('08305', 'Vilafranca del Penedès', 'Alt Penedès', 'Barcelona'),
  ('08306', 'Vilalba Sasserra', 'Vallès Oriental', 'Barcelona'),
  ('08307', 'Vilanova i la Geltrú', 'Garraf', 'Barcelona'),
  ('08308', 'Viver i Serrateix', 'Berguedà', 'Barcelona'),
  ('08901', 'Rupit i Pruit', 'Osona', 'Barcelona'),
  ('08902', 'Vilanova del Vallès', 'Vallès Oriental', 'Barcelona'),
  ('08903', 'Sant Julià de Cerdanyola', 'Berguedà', 'Barcelona'),
  ('08904', 'Badia del Vallès', 'Vallès Occidental', 'Barcelona'),
  ('08905', 'Palma de Cervelló, la', 'Baix Llobregat', 'Barcelona'),
  ('17001', 'Agullana', 'Alt Empordà', 'Girona'),
  ('17002', 'Aiguaviva', 'Gironès', 'Girona'),
  ('17003', 'Albanyà', 'Alt Empordà', 'Girona'),
  ('17004', 'Albons', 'Baix Empordà', 'Girona'),
  ('17005', 'Far d''Empordà, el', 'Alt Empordà', 'Girona'),
  ('17006', 'Alp', 'Cerdanya', 'Girona'),
  ('17007', 'Amer', 'Selva', 'Girona'),
  ('17008', 'Anglès', 'Selva', 'Girona'),
  ('17009', 'Arbúcies', 'Selva', 'Girona'),
  ('17010', 'Argelaguer', 'Garrotxa', 'Girona'),
  ('17011', 'Armentera, l''', 'Alt Empordà', 'Girona'),
  ('17012', 'Avinyonet de Puigventós', 'Alt Empordà', 'Girona'),
  ('17013', 'Begur', 'Baix Empordà', 'Girona'),
  ('17014', 'Vajol, la', 'Alt Empordà', 'Girona'),
  ('17015', 'Banyoles', 'Pla de l''Estany', 'Girona'),
  ('17016', 'Bàscara', 'Alt Empordà', 'Girona'),
  ('17018', 'Bellcaire d''Empordà', 'Baix Empordà', 'Girona'),
  ('17019', 'Besalú', 'Garrotxa', 'Girona'),
  ('17020', 'Bescanó', 'Gironès', 'Girona'),
  ('17021', 'Beuda', 'Garrotxa', 'Girona'),
  ('17022', 'Bisbal d''Empordà, la', 'Baix Empordà', 'Girona'),
  ('17023', 'Blanes', 'Selva', 'Girona'),
  ('17024', 'Bolvir', 'Cerdanya', 'Girona'),
  ('17025', 'Bordils', 'Gironès', 'Girona'),
  ('17026', 'Borrassà', 'Alt Empordà', 'Girona'),
  ('17027', 'Breda', 'Selva', 'Girona'),
  ('17028', 'Brunyola i Sant Martí Sapresa', 'Selva', 'Girona'),
  ('17029', 'Boadella i les Escaules', 'Alt Empordà', 'Girona'),
  ('17030', 'Cabanes', 'Alt Empordà', 'Girona'),
  ('17031', 'Cabanelles', 'Alt Empordà', 'Girona'),
  ('17032', 'Cadaqués', 'Alt Empordà', 'Girona'),
  ('17033', 'Caldes de Malavella', 'Selva', 'Girona'),
  ('17034', 'Calonge i Sant Antoni', 'Baix Empordà', 'Girona'),
  ('17035', 'Camós', 'Pla de l''Estany', 'Girona'),
  ('17036', 'Campdevànol', 'Ripollès', 'Girona'),
  ('17037', 'Campelles', 'Ripollès', 'Girona'),
  ('17038', 'Campllong', 'Gironès', 'Girona'),
  ('17039', 'Camprodon', 'Ripollès', 'Girona'),
  ('17040', 'Canet d''Adri', 'Gironès', 'Girona'),
  ('17041', 'Cantallops', 'Alt Empordà', 'Girona'),
  ('17042', 'Capmany', 'Alt Empordà', 'Girona'),
  ('17043', 'Queralbs', 'Ripollès', 'Girona'),
  ('17044', 'Cassà de la Selva', 'Gironès', 'Girona'),
  ('17046', 'Castellfollit de la Roca', 'Garrotxa', 'Girona'),
  ('17047', 'Castelló d''Empúries', 'Alt Empordà', 'Girona'),
  ('17048', 'Castell d''Aro, Platja d''Aro i s''Agaró', 'Baix Empordà', 'Girona'),
  ('17049', 'Celrà', 'Gironès', 'Girona'),
  ('17050', 'Cervià de Ter', 'Gironès', 'Girona'),
  ('17051', 'Cistella', 'Alt Empordà', 'Girona'),
  ('17052', 'Siurana', 'Alt Empordà', 'Girona'),
  ('17054', 'Colera', 'Alt Empordà', 'Girona'),
  ('17055', 'Colomers', 'Baix Empordà', 'Girona'),
  ('17056', 'Cornellà del Terri', 'Pla de l''Estany', 'Girona'),
  ('17057', 'Corçà', 'Baix Empordà', 'Girona'),
  ('17058', 'Crespià', 'Pla de l''Estany', 'Girona'),
  ('17060', 'Darnius', 'Alt Empordà', 'Girona'),
  ('17061', 'Das', 'Cerdanya', 'Girona'),
  ('17062', 'Escala, l''', 'Alt Empordà', 'Girona'),
  ('17063', 'Espinelves', 'Osona', 'Girona'),
  ('17064', 'Espolla', 'Alt Empordà', 'Girona'),
  ('17065', 'Esponellà', 'Pla de l''Estany', 'Girona'),
  ('17066', 'Figueres', 'Alt Empordà', 'Girona'),
  ('17067', 'Flaçà', 'Gironès', 'Girona'),
  ('17068', 'Foixà', 'Baix Empordà', 'Girona'),
  ('17069', 'Fontanals de Cerdanya', 'Cerdanya', 'Girona'),
  ('17070', 'Fontanilles', 'Baix Empordà', 'Girona'),
  ('17071', 'Fontcoberta', 'Pla de l''Estany', 'Girona'),
  ('17073', 'Fornells de la Selva', 'Gironès', 'Girona'),
  ('17074', 'Fortià', 'Alt Empordà', 'Girona'),
  ('17075', 'Garrigàs', 'Alt Empordà', 'Girona'),
  ('17076', 'Garrigoles', 'Baix Empordà', 'Girona'),
  ('17077', 'Garriguella', 'Alt Empordà', 'Girona'),
  ('17078', 'Ger', 'Cerdanya', 'Girona'),
  ('17079', 'Girona', 'Gironès', 'Girona'),
  ('17080', 'Gombrèn', 'Ripollès', 'Girona'),
  ('17081', 'Gualta', 'Baix Empordà', 'Girona'),
  ('17082', 'Guils de Cerdanya', 'Cerdanya', 'Girona'),
  ('17083', 'Hostalric', 'Selva', 'Girona'),
  ('17084', 'Isòvol', 'Cerdanya', 'Girona'),
  ('17085', 'Jafre', 'Baix Empordà', 'Girona'),
  ('17086', 'Jonquera, la', 'Alt Empordà', 'Girona'),
  ('17087', 'Juià', 'Gironès', 'Girona'),
  ('17088', 'Lladó', 'Alt Empordà', 'Girona'),
  ('17089', 'Llagostera', 'Gironès', 'Girona'),
  ('17090', 'Llambilles', 'Gironès', 'Girona'),
  ('17091', 'Llanars', 'Ripollès', 'Girona'),
  ('17092', 'Llançà', 'Alt Empordà', 'Girona'),
  ('17093', 'Llers', 'Alt Empordà', 'Girona'),
  ('17094', 'Llívia', 'Cerdanya', 'Girona'),
  ('17095', 'Lloret de Mar', 'Selva', 'Girona'),
  ('17096', 'Llosses, les', 'Ripollès', 'Girona'),
  ('17097', 'Madremanya', 'Gironès', 'Girona'),
  ('17098', 'Maià de Montcal', 'Garrotxa', 'Girona'),
  ('17099', 'Meranges', 'Cerdanya', 'Girona'),
  ('17100', 'Masarac i Vilarnadal', 'Alt Empordà', 'Girona'),
  ('17101', 'Massanes', 'Selva', 'Girona'),
  ('17102', 'Maçanet de Cabrenys', 'Alt Empordà', 'Girona'),
  ('17103', 'Maçanet de la Selva', 'Selva', 'Girona'),
  ('17105', 'Mieres', 'Garrotxa', 'Girona'),
  ('17106', 'Mollet de Peralada', 'Alt Empordà', 'Girona'),
  ('17107', 'Molló', 'Ripollès', 'Girona'),
  ('17109', 'Montagut i Oix', 'Garrotxa', 'Girona'),
  ('17110', 'Mont-ras', 'Baix Empordà', 'Girona'),
  ('17111', 'Navata', 'Alt Empordà', 'Girona'),
  ('17112', 'Ogassa', 'Ripollès', 'Girona'),
  ('17114', 'Olot', 'Garrotxa', 'Girona'),
  ('17115', 'Ordis', 'Alt Empordà', 'Girona'),
  ('17116', 'Osor', 'Selva', 'Girona'),
  ('17117', 'Palafrugell', 'Baix Empordà', 'Girona'),
  ('17118', 'Palamós', 'Baix Empordà', 'Girona'),
  ('17119', 'Palau de Santa Eulàlia', 'Alt Empordà', 'Girona'),
  ('17120', 'Palau-saverdera', 'Alt Empordà', 'Girona'),
  ('17121', 'Palau-sator', 'Baix Empordà', 'Girona'),
  ('17123', 'Palol de Revardit', 'Pla de l''Estany', 'Girona'),
  ('17124', 'Pals', 'Baix Empordà', 'Girona'),
  ('17125', 'Pardines', 'Ripollès', 'Girona'),
  ('17126', 'Parlavà', 'Baix Empordà', 'Girona'),
  ('17128', 'Pau', 'Alt Empordà', 'Girona'),
  ('17129', 'Pedret i Marzà', 'Alt Empordà', 'Girona'),
  ('17130', 'Pera, la', 'Baix Empordà', 'Girona'),
  ('17132', 'Peralada', 'Alt Empordà', 'Girona'),
  ('17133', 'Planes d''Hostoles, les', 'Garrotxa', 'Girona'),
  ('17134', 'Planoles', 'Ripollès', 'Girona'),
  ('17135', 'Pont de Molins', 'Alt Empordà', 'Girona'),
  ('17136', 'Pontós', 'Alt Empordà', 'Girona'),
  ('17137', 'Porqueres', 'Pla de l''Estany', 'Girona'),
  ('17138', 'Portbou', 'Alt Empordà', 'Girona'),
  ('17139', 'Preses, les', 'Garrotxa', 'Girona'),
  ('17140', 'Port de la Selva, el', 'Alt Empordà', 'Girona'),
  ('17141', 'Puigcerdà', 'Cerdanya', 'Girona'),
  ('17142', 'Quart', 'Gironès', 'Girona'),
  ('17143', 'Rabós', 'Alt Empordà', 'Girona'),
  ('17144', 'Regencós', 'Baix Empordà', 'Girona'),
  ('17145', 'Ribes de Freser', 'Ripollès', 'Girona'),
  ('17146', 'Riells i Viabrea', 'Selva', 'Girona'),
  ('17147', 'Ripoll', 'Ripollès', 'Girona'),
  ('17148', 'Riudarenes', 'Selva', 'Girona'),
  ('17149', 'Riudaura', 'Garrotxa', 'Girona'),
  ('17150', 'Riudellots de la Selva', 'Selva', 'Girona'),
  ('17151', 'Riumors', 'Alt Empordà', 'Girona'),
  ('17152', 'Roses', 'Alt Empordà', 'Girona'),
  ('17153', 'Rupià', 'Baix Empordà', 'Girona'),
  ('17154', 'Sales de Llierca', 'Garrotxa', 'Girona'),
  ('17155', 'Salt', 'Gironès', 'Girona'),
  ('17157', 'Sant Andreu Salou', 'Gironès', 'Girona'),
  ('17158', 'Sant Climent Sescebes', 'Alt Empordà', 'Girona'),
  ('17159', 'Sant Feliu de Buixalleu', 'Selva', 'Girona'),
  ('17160', 'Sant Feliu de Guíxols', 'Baix Empordà', 'Girona'),
  ('17161', 'Sant Feliu de Pallerols', 'Garrotxa', 'Girona'),
  ('17162', 'Sant Ferriol', 'Garrotxa', 'Girona'),
  ('17163', 'Sant Gregori', 'Gironès', 'Girona'),
  ('17164', 'Sant Hilari Sacalm', 'Selva', 'Girona'),
  ('17165', 'Sant Jaume de Llierca', 'Garrotxa', 'Girona'),
  ('17166', 'Sant Jordi Desvalls', 'Gironès', 'Girona'),
  ('17167', 'Sant Joan de les Abadesses', 'Ripollès', 'Girona'),
  ('17168', 'Sant Joan de Mollet', 'Gironès', 'Girona'),
  ('17169', 'Sant Julià de Ramis', 'Gironès', 'Girona'),
  ('17170', 'Vallfogona de Ripollès', 'Ripollès', 'Girona'),
  ('17171', 'Sant Llorenç de la Muga', 'Alt Empordà', 'Girona'),
  ('17172', 'Sant Martí de Llémena', 'Gironès', 'Girona'),
  ('17173', 'Sant Martí Vell', 'Gironès', 'Girona'),
  ('17174', 'Sant Miquel de Campmajor', 'Pla de l''Estany', 'Girona'),
  ('17175', 'Sant Miquel de Fluvià', 'Alt Empordà', 'Girona'),
  ('17176', 'Sant Mori', 'Alt Empordà', 'Girona'),
  ('17177', 'Sant Pau de Segúries', 'Ripollès', 'Girona'),
  ('17178', 'Sant Pere Pescador', 'Alt Empordà', 'Girona'),
  ('17180', 'Santa Coloma de Farners', 'Selva', 'Girona'),
  ('17181', 'Santa Cristina d''Aro', 'Baix Empordà', 'Girona'),
  ('17182', 'Santa Llogaia d''Àlguema', 'Alt Empordà', 'Girona'),
  ('17183', 'Sant Aniol de Finestres', 'Garrotxa', 'Girona'),
  ('17184', 'Santa Pau', 'Garrotxa', 'Girona'),
  ('17185', 'Sant Joan les Fonts', 'Garrotxa', 'Girona'),
  ('17186', 'Sarrià de Ter', 'Gironès', 'Girona'),
  ('17187', 'Saus, Camallera i Llampaies', 'Alt Empordà', 'Girona'),
  ('17188', 'Selva de Mar, la', 'Alt Empordà', 'Girona'),
  ('17189', 'Cellera de Ter, la', 'Selva', 'Girona'),
  ('17190', 'Serinyà', 'Pla de l''Estany', 'Girona'),
  ('17191', 'Serra de Daró', 'Baix Empordà', 'Girona'),
  ('17192', 'Setcases', 'Ripollès', 'Girona'),
  ('17193', 'Sils', 'Selva', 'Girona'),
  ('17194', 'Susqueda', 'Selva', 'Girona'),
  ('17195', 'Tallada d''Empordà, la', 'Baix Empordà', 'Girona'),
  ('17196', 'Terrades', 'Alt Empordà', 'Girona'),
  ('17197', 'Torrent', 'Baix Empordà', 'Girona'),
  ('17198', 'Torroella de Fluvià', 'Alt Empordà', 'Girona'),
  ('17199', 'Torroella de Montgrí', 'Baix Empordà', 'Girona'),
  ('17200', 'Tortellà', 'Garrotxa', 'Girona'),
  ('17201', 'Toses', 'Ripollès', 'Girona'),
  ('17202', 'Tossa de Mar', 'Selva', 'Girona'),
  ('17203', 'Ultramort', 'Baix Empordà', 'Girona'),
  ('17204', 'Ullà', 'Baix Empordà', 'Girona'),
  ('17205', 'Ullastret', 'Baix Empordà', 'Girona'),
  ('17206', 'Urús', 'Cerdanya', 'Girona'),
  ('17207', 'Vall d''en Bas, la', 'Garrotxa', 'Girona'),
  ('17208', 'Vall de Bianya, la', 'Garrotxa', 'Girona'),
  ('17209', 'Vall-llobrega', 'Baix Empordà', 'Girona'),
  ('17210', 'Ventalló', 'Alt Empordà', 'Girona'),
  ('17211', 'Verges', 'Baix Empordà', 'Girona'),
  ('17212', 'Vidrà', 'Osona', 'Girona'),
  ('17213', 'Vidreres', 'Selva', 'Girona'),
  ('17214', 'Vilabertran', 'Alt Empordà', 'Girona'),
  ('17215', 'Vilablareix', 'Gironès', 'Girona'),
  ('17216', 'Viladasens', 'Gironès', 'Girona'),
  ('17217', 'Viladamat', 'Alt Empordà', 'Girona'),
  ('17218', 'Vilademuls', 'Pla de l''Estany', 'Girona'),
  ('17220', 'Viladrau', 'Osona', 'Girona'),
  ('17221', 'Vilafant', 'Alt Empordà', 'Girona'),
  ('17222', 'Vilaür', 'Alt Empordà', 'Girona'),
  ('17223', 'Vilajuïga', 'Alt Empordà', 'Girona'),
  ('17224', 'Vilallonga de Ter', 'Ripollès', 'Girona'),
  ('17225', 'Vilamacolum', 'Alt Empordà', 'Girona'),
  ('17226', 'Vilamalla', 'Alt Empordà', 'Girona'),
  ('17227', 'Vilamaniscle', 'Alt Empordà', 'Girona'),
  ('17228', 'Vilanant', 'Alt Empordà', 'Girona'),
  ('17230', 'Vila-sacra', 'Alt Empordà', 'Girona'),
  ('17232', 'Vilopriu', 'Baix Empordà', 'Girona'),
  ('17233', 'Vilobí d''Onyar', 'Selva', 'Girona'),
  ('17234', 'Biure', 'Alt Empordà', 'Girona'),
  ('17901', 'Cruïlles, Monells i Sant Sadurní de l''Heura', 'Baix Empordà', 'Girona'),
  ('17902', 'Forallac', 'Baix Empordà', 'Girona'),
  ('17903', 'Sant Julià del Llor i Bonmatí', 'Selva', 'Girona'),
  ('25001', 'Abella de la Conca', 'Pallars Jussà', 'Lleida'),
  ('25002', 'Àger', 'Noguera', 'Lleida'),
  ('25003', 'Agramunt', 'Urgell', 'Lleida'),
  ('25004', 'Alamús, els', 'Segrià', 'Lleida'),
  ('25005', 'Alàs i Cerc', 'Alt Urgell', 'Lleida'),
  ('25006', 'Albagés, l''', 'Garrigues', 'Lleida'),
  ('25007', 'Albatàrrec', 'Segrià', 'Lleida'),
  ('25008', 'Albesa', 'Noguera', 'Lleida'),
  ('25009', 'Albi, l''', 'Garrigues', 'Lleida'),
  ('25010', 'Alcanó', 'Segrià', 'Lleida'),
  ('25011', 'Alcarràs', 'Segrià', 'Lleida'),
  ('25012', 'Alcoletge', 'Segrià', 'Lleida'),
  ('25013', 'Alfarràs', 'Segrià', 'Lleida'),
  ('25014', 'Alfés', 'Segrià', 'Lleida'),
  ('25015', 'Algerri', 'Noguera', 'Lleida'),
  ('25016', 'Alguaire', 'Segrià', 'Lleida'),
  ('25017', 'Alins', 'Pallars Sobirà', 'Lleida'),
  ('25019', 'Almacelles', 'Segrià', 'Lleida'),
  ('25020', 'Almatret', 'Segrià', 'Lleida'),
  ('25021', 'Almenar', 'Segrià', 'Lleida'),
  ('25022', 'Alòs de Balaguer', 'Noguera', 'Lleida'),
  ('25023', 'Alpicat', 'Segrià', 'Lleida'),
  ('25024', 'Alt Àneu', 'Pallars Sobirà', 'Lleida'),
  ('25025', 'Naut Aran', 'Aran', 'Lleida'),
  ('25027', 'Anglesola', 'Urgell', 'Lleida'),
  ('25029', 'Arbeca', 'Garrigues', 'Lleida'),
  ('25030', 'Pont de Bar, el', 'Alt Urgell', 'Lleida'),
  ('25031', 'Arres', 'Aran', 'Lleida'),
  ('25032', 'Arsèguel', 'Alt Urgell', 'Lleida'),
  ('25033', 'Artesa de Lleida', 'Segrià', 'Lleida'),
  ('25034', 'Artesa de Segre', 'Noguera', 'Lleida'),
  ('25035', 'Sentiu de Sió, la', 'Noguera', 'Lleida'),
  ('25036', 'Aspa', 'Segrià', 'Lleida'),
  ('25037', 'Avellanes i Santa Linya, les', 'Noguera', 'Lleida'),
  ('25038', 'Aitona', 'Segrià', 'Lleida'),
  ('25039', 'Baix Pallars', 'Pallars Sobirà', 'Lleida'),
  ('25040', 'Balaguer', 'Noguera', 'Lleida'),
  ('25041', 'Barbens', 'Pla d''Urgell', 'Lleida'),
  ('25042', 'Baronia de Rialb, la', 'Noguera', 'Lleida'),
  ('25043', 'Vall de Boí, la', 'Alta Ribagorça', 'Lleida'),
  ('25044', 'Bassella', 'Alt Urgell', 'Lleida'),
  ('25045', 'Bausen', 'Aran', 'Lleida'),
  ('25046', 'Belianes', 'Urgell', 'Lleida'),
  ('25047', 'Bellcaire d''Urgell', 'Noguera', 'Lleida'),
  ('25048', 'Bell-lloc d''Urgell', 'Pla d''Urgell', 'Lleida'),
  ('25049', 'Bellmunt d''Urgell', 'Noguera', 'Lleida'),
  ('25050', 'Bellpuig', 'Urgell', 'Lleida'),
  ('25051', 'Bellver de Cerdanya', 'Cerdanya', 'Lleida'),
  ('25052', 'Bellvís', 'Pla d''Urgell', 'Lleida'),
  ('25053', 'Benavent de Segrià', 'Segrià', 'Lleida'),
  ('25055', 'Biosca', 'Solsonès', 'Lleida'),
  ('25056', 'Bovera', 'Garrigues', 'Lleida'),
  ('25057', 'Bòrdes, Es', 'Aran', 'Lleida'),
  ('25058', 'Borges Blanques, les', 'Garrigues', 'Lleida'),
  ('25059', 'Bossòst', 'Aran', 'Lleida'),
  ('25060', 'Cabanabona', 'Noguera', 'Lleida'),
  ('25061', 'Cabó', 'Alt Urgell', 'Lleida'),
  ('25062', 'Camarasa', 'Noguera', 'Lleida'),
  ('25063', 'Canejan', 'Aran', 'Lleida'),
  ('25064', 'Castellar de la Ribera', 'Solsonès', 'Lleida'),
  ('25067', 'Castelldans', 'Garrigues', 'Lleida'),
  ('25068', 'Castellnou de Seana', 'Pla d''Urgell', 'Lleida'),
  ('25069', 'Castelló de Farfanya', 'Noguera', 'Lleida'),
  ('25070', 'Castellserà', 'Urgell', 'Lleida'),
  ('25071', 'Cava', 'Alt Urgell', 'Lleida'),
  ('25072', 'Cervera', 'Segarra', 'Lleida'),
  ('25073', 'Cervià de les Garrigues', 'Garrigues', 'Lleida'),
  ('25074', 'Ciutadilla', 'Urgell', 'Lleida'),
  ('25075', 'Clariana de Cardener', 'Solsonès', 'Lleida'),
  ('25076', 'Cogul, el', 'Garrigues', 'Lleida'),
  ('25077', 'Coll de Nargó', 'Alt Urgell', 'Lleida'),
  ('25078', 'Corbins', 'Segrià', 'Lleida'),
  ('25079', 'Cubells', 'Noguera', 'Lleida'),
  ('25081', 'Espluga Calba, l''', 'Garrigues', 'Lleida'),
  ('25082', 'Espot', 'Pallars Sobirà', 'Lleida'),
  ('25085', 'Estaràs', 'Segarra', 'Lleida'),
  ('25086', 'Esterri d''Àneu', 'Pallars Sobirà', 'Lleida'),
  ('25087', 'Esterri de Cardós', 'Pallars Sobirà', 'Lleida'),
  ('25088', 'Estamariu', 'Alt Urgell', 'Lleida'),
  ('25089', 'Farrera', 'Pallars Sobirà', 'Lleida'),
  ('25092', 'Floresta, la', 'Garrigues', 'Lleida'),
  ('25093', 'Fondarella', 'Pla d''Urgell', 'Lleida'),
  ('25094', 'Foradada', 'Noguera', 'Lleida'),
  ('25096', 'Fuliola, la', 'Urgell', 'Lleida'),
  ('25097', 'Fulleda', 'Garrigues', 'Lleida'),
  ('25098', 'Gavet de la Conca', 'Pallars Jussà', 'Lleida'),
  ('25099', 'Golmés', 'Pla d''Urgell', 'Lleida'),
  ('25100', 'Gósol', 'Berguedà', 'Lleida'),
  ('25101', 'Granadella, la', 'Garrigues', 'Lleida'),
  ('25102', 'Granja d''Escarp, la', 'Segrià', 'Lleida'),
  ('25103', 'Granyanella', 'Segarra', 'Lleida'),
  ('25104', 'Granyena de Segarra', 'Segarra', 'Lleida'),
  ('25105', 'Granyena de les Garrigues', 'Garrigues', 'Lleida'),
  ('25109', 'Guimerà', 'Urgell', 'Lleida'),
  ('25110', 'Guissona', 'Segarra', 'Lleida'),
  ('25111', 'Guixers', 'Solsonès', 'Lleida'),
  ('25112', 'Ivars de Noguera', 'Noguera', 'Lleida'),
  ('25113', 'Ivars d''Urgell', 'Pla d''Urgell', 'Lleida'),
  ('25114', 'Ivorra', 'Segarra', 'Lleida'),
  ('25115', 'Isona i Conca Dellà', 'Pallars Jussà', 'Lleida'),
  ('25118', 'Juncosa', 'Garrigues', 'Lleida'),
  ('25119', 'Juneda', 'Garrigues', 'Lleida'),
  ('25120', 'Lleida', 'Segrià', 'Lleida'),
  ('25121', 'Les', 'Aran', 'Lleida'),
  ('25122', 'Linyola', 'Pla d''Urgell', 'Lleida'),
  ('25123', 'Lladorre', 'Pallars Sobirà', 'Lleida'),
  ('25124', 'Lladurs', 'Solsonès', 'Lleida'),
  ('25125', 'Llardecans', 'Segrià', 'Lleida'),
  ('25126', 'Llavorsí', 'Pallars Sobirà', 'Lleida'),
  ('25127', 'Lles de Cerdanya', 'Cerdanya', 'Lleida'),
  ('25128', 'Llimiana', 'Pallars Jussà', 'Lleida'),
  ('25129', 'Llobera', 'Solsonès', 'Lleida'),
  ('25130', 'Maldà', 'Urgell', 'Lleida'),
  ('25131', 'Massalcoreig', 'Segrià', 'Lleida'),
  ('25132', 'Massoteres', 'Segarra', 'Lleida'),
  ('25133', 'Maials', 'Segrià', 'Lleida'),
  ('25134', 'Menàrguens', 'Noguera', 'Lleida'),
  ('25135', 'Miralcamp', 'Pla d''Urgell', 'Lleida'),
  ('25136', 'Molsosa, la', 'Solsonès', 'Lleida'),
  ('25137', 'Mollerussa', 'Pla d''Urgell', 'Lleida'),
  ('25138', 'Montgai', 'Noguera', 'Lleida'),
  ('25139', 'Montellà i Martinet', 'Cerdanya', 'Lleida'),
  ('25140', 'Montferrer i Castellbò', 'Alt Urgell', 'Lleida'),
  ('25141', 'Montoliu de Segarra', 'Segarra', 'Lleida'),
  ('25142', 'Montoliu de Lleida', 'Segrià', 'Lleida'),
  ('25143', 'Montornès de Segarra', 'Segarra', 'Lleida'),
  ('25145', 'Nalec', 'Urgell', 'Lleida'),
  ('25146', 'Navès', 'Solsonès', 'Lleida'),
  ('25148', 'Odèn', 'Solsonès', 'Lleida'),
  ('25149', 'Oliana', 'Alt Urgell', 'Lleida'),
  ('25150', 'Oliola', 'Noguera', 'Lleida'),
  ('25151', 'Olius', 'Solsonès', 'Lleida'),
  ('25152', 'Oluges, les', 'Segarra', 'Lleida'),
  ('25153', 'Omellons, els', 'Garrigues', 'Lleida'),
  ('25154', 'Omells de na Gaia, els', 'Urgell', 'Lleida'),
  ('25155', 'Organyà', 'Alt Urgell', 'Lleida'),
  ('25156', 'Os de Balaguer', 'Noguera', 'Lleida'),
  ('25157', 'Ossó de Sió', 'Urgell', 'Lleida'),
  ('25158', 'Palau d''Anglesola, el', 'Pla d''Urgell', 'Lleida'),
  ('25161', 'Conca de Dalt', 'Pallars Jussà', 'Lleida'),
  ('25163', 'Coma i la Pedra, la', 'Solsonès', 'Lleida'),
  ('25164', 'Penelles', 'Noguera', 'Lleida'),
  ('25165', 'Peramola', 'Alt Urgell', 'Lleida'),
  ('25166', 'Pinell de Solsonès', 'Solsonès', 'Lleida'),
  ('25167', 'Pinós', 'Solsonès', 'Lleida'),
  ('25168', 'Poal, el', 'Pla d''Urgell', 'Lleida'),
  ('25169', 'Pobla de Cérvoles, la', 'Garrigues', 'Lleida'),
  ('25170', 'Bellaguarda', 'Garrigues', 'Lleida'),
  ('25171', 'Pobla de Segur, la', 'Pallars Jussà', 'Lleida'),
  ('25172', 'Ponts', 'Noguera', 'Lleida'),
  ('25173', 'Pont de Suert, el', 'Alta Ribagorça', 'Lleida'),
  ('25174', 'Portella, la', 'Segrià', 'Lleida'),
  ('25175', 'Prats i Sansor', 'Cerdanya', 'Lleida'),
  ('25176', 'Preixana', 'Urgell', 'Lleida'),
  ('25177', 'Preixens', 'Noguera', 'Lleida'),
  ('25179', 'Prullans', 'Cerdanya', 'Lleida'),
  ('25180', 'Puiggròs', 'Garrigues', 'Lleida'),
  ('25181', 'Puigverd d''Agramunt', 'Urgell', 'Lleida'),
  ('25182', 'Puigverd de Lleida', 'Segrià', 'Lleida'),
  ('25183', 'Rialp', 'Pallars Sobirà', 'Lleida'),
  ('25185', 'Ribera d''Urgellet', 'Alt Urgell', 'Lleida'),
  ('25186', 'Riner', 'Solsonès', 'Lleida'),
  ('25189', 'Rosselló', 'Segrià', 'Lleida'),
  ('25190', 'Salàs de Pallars', 'Pallars Jussà', 'Lleida'),
  ('25191', 'Sanaüja', 'Segarra', 'Lleida'),
  ('25192', 'Sant Guim de Freixenet', 'Segarra', 'Lleida'),
  ('25193', 'Sant Llorenç de Morunys', 'Solsonès', 'Lleida'),
  ('25194', 'Sant Ramon', 'Segarra', 'Lleida'),
  ('25196', 'Sant Esteve de la Sarga', 'Pallars Jussà', 'Lleida'),
  ('25197', 'Sant Guim de la Plana', 'Segarra', 'Lleida'),
  ('25200', 'Sarroca de Lleida', 'Segrià', 'Lleida'),
  ('25201', 'Sarroca de Bellera', 'Pallars Jussà', 'Lleida'),
  ('25202', 'Senterada', 'Pallars Jussà', 'Lleida'),
  ('25203', 'Seu d''Urgell, la', 'Alt Urgell', 'Lleida'),
  ('25204', 'Seròs', 'Segrià', 'Lleida'),
  ('25205', 'Sidamon', 'Pla d''Urgell', 'Lleida'),
  ('25206', 'Soleràs, el', 'Garrigues', 'Lleida'),
  ('25207', 'Solsona', 'Solsonès', 'Lleida'),
  ('25208', 'Soriguera', 'Pallars Sobirà', 'Lleida'),
  ('25209', 'Sort', 'Pallars Sobirà', 'Lleida'),
  ('25210', 'Soses', 'Segrià', 'Lleida'),
  ('25211', 'Sudanell', 'Segrià', 'Lleida'),
  ('25212', 'Sunyer', 'Segrià', 'Lleida'),
  ('25215', 'Talarn', 'Pallars Jussà', 'Lleida'),
  ('25216', 'Talavera', 'Segarra', 'Lleida'),
  ('25217', 'Tàrrega', 'Urgell', 'Lleida'),
  ('25218', 'Tarrés', 'Garrigues', 'Lleida'),
  ('25219', 'Tarroja de Segarra', 'Segarra', 'Lleida'),
  ('25220', 'Térmens', 'Noguera', 'Lleida'),
  ('25221', 'Tírvia', 'Pallars Sobirà', 'Lleida'),
  ('25222', 'Tiurana', 'Noguera', 'Lleida'),
  ('25223', 'Torà', 'Solsonès', 'Lleida'),
  ('25224', 'Torms, els', 'Garrigues', 'Lleida'),
  ('25225', 'Tornabous', 'Urgell', 'Lleida'),
  ('25226', 'Torrebesses', 'Segrià', 'Lleida'),
  ('25227', 'Torre de Cabdella, la', 'Pallars Jussà', 'Lleida'),
  ('25228', 'Torrefarrera', 'Segrià', 'Lleida'),
  ('25230', 'Torregrossa', 'Pla d''Urgell', 'Lleida'),
  ('25231', 'Torrelameu', 'Noguera', 'Lleida'),
  ('25232', 'Torres de Segre', 'Segrià', 'Lleida'),
  ('25233', 'Torre-serona', 'Segrià', 'Lleida'),
  ('25234', 'Tremp', 'Pallars Jussà', 'Lleida'),
  ('25238', 'Vallbona de les Monges', 'Urgell', 'Lleida'),
  ('25239', 'Valls de Valira, les', 'Alt Urgell', 'Lleida'),
  ('25240', 'Vallfogona de Balaguer', 'Noguera', 'Lleida'),
  ('25242', 'Verdú', 'Urgell', 'Lleida'),
  ('25243', 'Vielha e Mijaran', 'Aran', 'Lleida'),
  ('25244', 'Vilagrassa', 'Urgell', 'Lleida'),
  ('25245', 'Vilaller', 'Alta Ribagorça', 'Lleida'),
  ('25247', 'Vilamòs', 'Aran', 'Lleida'),
  ('25248', 'Vilanova de Bellpuig', 'Pla d''Urgell', 'Lleida'),
  ('25249', 'Vilanova de l''Aguda', 'Noguera', 'Lleida'),
  ('25250', 'Vilanova de Meià', 'Noguera', 'Lleida'),
  ('25251', 'Vilanova de Segrià', 'Segrià', 'Lleida'),
  ('25252', 'Vila-sana', 'Pla d''Urgell', 'Lleida'),
  ('25253', 'Vilosell, el', 'Garrigues', 'Lleida'),
  ('25254', 'Vilanova de la Barca', 'Segrià', 'Lleida'),
  ('25255', 'Vinaixa', 'Garrigues', 'Lleida'),
  ('25901', 'Vall de Cardós', 'Pallars Sobirà', 'Lleida'),
  ('25902', 'Sant Martí de Riucorb', 'Urgell', 'Lleida'),
  ('25903', 'Guingueta d''Àneu, la', 'Pallars Sobirà', 'Lleida'),
  ('25904', 'Castell de Mur', 'Pallars Jussà', 'Lleida'),
  ('25905', 'Ribera d''Ondara', 'Segarra', 'Lleida'),
  ('25906', 'Valls d''Aguilar, les', 'Alt Urgell', 'Lleida'),
  ('25907', 'Torrefeta i Florejacs', 'Segarra', 'Lleida'),
  ('25908', 'Fígols i Alinyà', 'Alt Urgell', 'Lleida'),
  ('25909', 'Vansa i Fórnols, la', 'Alt Urgell', 'Lleida'),
  ('25910', 'Josa i Tuixén', 'Alt Urgell', 'Lleida'),
  ('25911', 'Plans de Sió, els', 'Segarra', 'Lleida'),
  ('25912', 'Gimenells i el Pla de la Font', 'Segrià', 'Lleida'),
  ('25913', 'Riu de Cerdanya', 'Cerdanya', 'Lleida'),
  ('43001', 'Aiguamúrcia', 'Alt Camp', 'Tarragona'),
  ('43002', 'Albinyana', 'Baix Penedès', 'Tarragona'),
  ('43003', 'Albiol, l''', 'Baix Camp', 'Tarragona'),
  ('43004', 'Alcanar', 'Montsià', 'Tarragona'),
  ('43005', 'Alcover', 'Alt Camp', 'Tarragona'),
  ('43006', 'Aldover', 'Baix Ebre', 'Tarragona'),
  ('43007', 'Aleixar, l''', 'Baix Camp', 'Tarragona'),
  ('43008', 'Alfara de Carles', 'Baix Ebre', 'Tarragona'),
  ('43009', 'Alforja', 'Baix Camp', 'Tarragona'),
  ('43010', 'Alió', 'Alt Camp', 'Tarragona'),
  ('43011', 'Almoster', 'Baix Camp', 'Tarragona'),
  ('43012', 'Altafulla', 'Tarragonès', 'Tarragona'),
  ('43013', 'Ametlla de Mar, l''', 'Baix Ebre', 'Tarragona'),
  ('43014', 'Amposta', 'Montsià', 'Tarragona'),
  ('43015', 'Arbolí', 'Baix Camp', 'Tarragona'),
  ('43016', 'Arboç, l''', 'Baix Penedès', 'Tarragona'),
  ('43017', 'Argentera, l''', 'Baix Camp', 'Tarragona'),
  ('43018', 'Arnes', 'Terra Alta', 'Tarragona'),
  ('43019', 'Ascó', 'Ribera d''Ebre', 'Tarragona'),
  ('43020', 'Banyeres del Penedès', 'Baix Penedès', 'Tarragona'),
  ('43021', 'Barberà de la Conca', 'Conca de Barberà', 'Tarragona'),
  ('43022', 'Batea', 'Terra Alta', 'Tarragona'),
  ('43023', 'Bellmunt del Priorat', 'Priorat', 'Tarragona'),
  ('43024', 'Bellvei', 'Baix Penedès', 'Tarragona'),
  ('43025', 'Benifallet', 'Baix Ebre', 'Tarragona'),
  ('43026', 'Benissanet', 'Ribera d''Ebre', 'Tarragona'),
  ('43027', 'Bisbal de Montsant, la', 'Priorat', 'Tarragona'),
  ('43028', 'Bisbal del Penedès, la', 'Baix Penedès', 'Tarragona'),
  ('43029', 'Blancafort', 'Conca de Barberà', 'Tarragona'),
  ('43030', 'Bonastre', 'Baix Penedès', 'Tarragona'),
  ('43031', 'Borges del Camp, les', 'Baix Camp', 'Tarragona'),
  ('43032', 'Bot', 'Terra Alta', 'Tarragona'),
  ('43033', 'Botarell', 'Baix Camp', 'Tarragona'),
  ('43034', 'Bràfim', 'Alt Camp', 'Tarragona'),
  ('43035', 'Cabacés', 'Priorat', 'Tarragona'),
  ('43036', 'Cabra del Camp', 'Alt Camp', 'Tarragona'),
  ('43037', 'Calafell', 'Baix Penedès', 'Tarragona'),
  ('43038', 'Cambrils', 'Baix Camp', 'Tarragona'),
  ('43039', 'Capafonts', 'Baix Camp', 'Tarragona'),
  ('43040', 'Capçanes', 'Priorat', 'Tarragona'),
  ('43041', 'Caseres', 'Terra Alta', 'Tarragona'),
  ('43042', 'Castellvell del Camp', 'Baix Camp', 'Tarragona'),
  ('43043', 'Catllar, el', 'Tarragonès', 'Tarragona'),
  ('43044', 'Sénia, la', 'Montsià', 'Tarragona'),
  ('43045', 'Colldejou', 'Baix Camp', 'Tarragona'),
  ('43046', 'Conesa', 'Conca de Barberà', 'Tarragona'),
  ('43047', 'Constantí', 'Tarragonès', 'Tarragona'),
  ('43048', 'Corbera d''Ebre', 'Terra Alta', 'Tarragona'),
  ('43049', 'Cornudella de Montsant', 'Priorat', 'Tarragona'),
  ('43050', 'Creixell', 'Tarragonès', 'Tarragona'),
  ('43051', 'Cunit', 'Baix Penedès', 'Tarragona'),
  ('43052', 'Xerta', 'Baix Ebre', 'Tarragona'),
  ('43053', 'Duesaigües', 'Baix Camp', 'Tarragona'),
  ('43054', 'Espluga de Francolí, l''', 'Conca de Barberà', 'Tarragona'),
  ('43055', 'Falset', 'Priorat', 'Tarragona'),
  ('43056', 'Fatarella, la', 'Terra Alta', 'Tarragona'),
  ('43057', 'Febró, la', 'Baix Camp', 'Tarragona'),
  ('43058', 'Figuera, la', 'Priorat', 'Tarragona'),
  ('43059', 'Figuerola del Camp', 'Alt Camp', 'Tarragona'),
  ('43060', 'Flix', 'Ribera d''Ebre', 'Tarragona'),
  ('43061', 'Forès', 'Conca de Barberà', 'Tarragona'),
  ('43062', 'Freginals', 'Montsià', 'Tarragona'),
  ('43063', 'Galera, la', 'Montsià', 'Tarragona'),
  ('43064', 'Gandesa', 'Terra Alta', 'Tarragona'),
  ('43065', 'Garcia', 'Ribera d''Ebre', 'Tarragona'),
  ('43066', 'Garidells, els', 'Alt Camp', 'Tarragona'),
  ('43067', 'Ginestar', 'Ribera d''Ebre', 'Tarragona'),
  ('43068', 'Godall', 'Montsià', 'Tarragona'),
  ('43069', 'Gratallops', 'Priorat', 'Tarragona'),
  ('43070', 'Guiamets, els', 'Priorat', 'Tarragona'),
  ('43071', 'Horta de Sant Joan', 'Terra Alta', 'Tarragona'),
  ('43072', 'Lloar, el', 'Priorat', 'Tarragona'),
  ('43073', 'Llorac', 'Conca de Barberà', 'Tarragona'),
  ('43074', 'Llorenç del Penedès', 'Baix Penedès', 'Tarragona'),
  ('43075', 'Margalef', 'Priorat', 'Tarragona'),
  ('43076', 'Marçà', 'Priorat', 'Tarragona'),
  ('43077', 'Mas de Barberans', 'Montsià', 'Tarragona'),
  ('43078', 'Masdenverge', 'Montsià', 'Tarragona'),
  ('43079', 'Masllorenç', 'Baix Penedès', 'Tarragona'),
  ('43080', 'Masó, la', 'Alt Camp', 'Tarragona'),
  ('43081', 'Maspujols', 'Baix Camp', 'Tarragona'),
  ('43082', 'Masroig, el', 'Priorat', 'Tarragona'),
  ('43083', 'Milà, el', 'Alt Camp', 'Tarragona'),
  ('43084', 'Miravet', 'Ribera d''Ebre', 'Tarragona'),
  ('43085', 'Molar, el', 'Priorat', 'Tarragona'),
  ('43086', 'Montblanc', 'Conca de Barberà', 'Tarragona'),
  ('43088', 'Montbrió del Camp', 'Baix Camp', 'Tarragona'),
  ('43089', 'Montferri', 'Alt Camp', 'Tarragona'),
  ('43090', 'Montmell, el', 'Baix Penedès', 'Tarragona'),
  ('43091', 'Mont-ral', 'Alt Camp', 'Tarragona'),
  ('43092', 'Mont-roig del Camp', 'Baix Camp', 'Tarragona'),
  ('43093', 'Móra d''Ebre', 'Ribera d''Ebre', 'Tarragona'),
  ('43094', 'Móra la Nova', 'Ribera d''Ebre', 'Tarragona'),
  ('43095', 'Morell, el', 'Tarragonès', 'Tarragona'),
  ('43096', 'Morera de Montsant, la', 'Priorat', 'Tarragona'),
  ('43097', 'Nou de Gaià, la', 'Tarragonès', 'Tarragona'),
  ('43098', 'Nulles', 'Alt Camp', 'Tarragona'),
  ('43099', 'Palma d''Ebre, la', 'Ribera d''Ebre', 'Tarragona'),
  ('43100', 'Pallaresos, els', 'Tarragonès', 'Tarragona'),
  ('43101', 'Passanant i Belltall', 'Conca de Barberà', 'Tarragona'),
  ('43102', 'Paüls', 'Baix Ebre', 'Tarragona'),
  ('43103', 'Perafort', 'Tarragonès', 'Tarragona'),
  ('43104', 'Perelló, el', 'Baix Ebre', 'Tarragona'),
  ('43105', 'Piles, les', 'Conca de Barberà', 'Tarragona'),
  ('43106', 'Pinell de Brai, el', 'Terra Alta', 'Tarragona'),
  ('43107', 'Pira', 'Conca de Barberà', 'Tarragona'),
  ('43108', 'Pla de Santa Maria, el', 'Alt Camp', 'Tarragona'),
  ('43109', 'Pobla de Mafumet, la', 'Tarragonès', 'Tarragona'),
  ('43110', 'Pobla de Massaluca, la', 'Terra Alta', 'Tarragona'),
  ('43111', 'Pobla de Montornès, la', 'Tarragonès', 'Tarragona'),
  ('43112', 'Poboleda', 'Priorat', 'Tarragona'),
  ('43113', 'Pont d''Armentera, el', 'Alt Camp', 'Tarragona'),
  ('43114', 'Porrera', 'Priorat', 'Tarragona'),
  ('43115', 'Pradell de la Teixeta', 'Priorat', 'Tarragona'),
  ('43116', 'Prades', 'Baix Camp', 'Tarragona'),
  ('43117', 'Prat de Comte', 'Terra Alta', 'Tarragona'),
  ('43118', 'Pratdip', 'Baix Camp', 'Tarragona'),
  ('43119', 'Puigpelat', 'Alt Camp', 'Tarragona'),
  ('43120', 'Querol', 'Alt Camp', 'Tarragona'),
  ('43121', 'Rasquera', 'Ribera d''Ebre', 'Tarragona'),
  ('43122', 'Renau', 'Tarragonès', 'Tarragona'),
  ('43123', 'Reus', 'Baix Camp', 'Tarragona'),
  ('43124', 'Riba, la', 'Alt Camp', 'Tarragona'),
  ('43125', 'Riba-roja d''Ebre', 'Ribera d''Ebre', 'Tarragona'),
  ('43126', 'Riera de Gaià, la', 'Tarragonès', 'Tarragona'),
  ('43127', 'Riudecanyes', 'Baix Camp', 'Tarragona'),
  ('43128', 'Riudecols', 'Baix Camp', 'Tarragona'),
  ('43129', 'Riudoms', 'Baix Camp', 'Tarragona'),
  ('43130', 'Rocafort de Queralt', 'Conca de Barberà', 'Tarragona'),
  ('43131', 'Roda de Berà', 'Tarragonès', 'Tarragona'),
  ('43132', 'Rodonyà', 'Alt Camp', 'Tarragona'),
  ('43133', 'Roquetes', 'Baix Ebre', 'Tarragona'),
  ('43134', 'Rourell, el', 'Alt Camp', 'Tarragona'),
  ('43135', 'Salomó', 'Tarragonès', 'Tarragona'),
  ('43136', 'Ràpita, la', 'Montsià', 'Tarragona'),
  ('43137', 'Sant Jaume dels Domenys', 'Baix Penedès', 'Tarragona'),
  ('43138', 'Santa Bàrbara', 'Montsià', 'Tarragona'),
  ('43139', 'Santa Coloma de Queralt', 'Conca de Barberà', 'Tarragona'),
  ('43140', 'Santa Oliva', 'Baix Penedès', 'Tarragona'),
  ('43141', 'Pontils', 'Conca de Barberà', 'Tarragona'),
  ('43142', 'Sarral', 'Conca de Barberà', 'Tarragona'),
  ('43143', 'Savallà del Comtat', 'Conca de Barberà', 'Tarragona'),
  ('43144', 'Secuita, la', 'Tarragonès', 'Tarragona'),
  ('43145', 'Selva del Camp, la', 'Baix Camp', 'Tarragona'),
  ('43146', 'Senan', 'Conca de Barberà', 'Tarragona'),
  ('43147', 'Solivella', 'Conca de Barberà', 'Tarragona'),
  ('43148', 'Tarragona', 'Tarragonès', 'Tarragona'),
  ('43149', 'Tivenys', 'Baix Ebre', 'Tarragona'),
  ('43150', 'Tivissa', 'Ribera d''Ebre', 'Tarragona'),
  ('43151', 'Torre de Fontaubella, la', 'Priorat', 'Tarragona'),
  ('43152', 'Torre de l''Espanyol, la', 'Ribera d''Ebre', 'Tarragona'),
  ('43153', 'Torredembarra', 'Tarragonès', 'Tarragona'),
  ('43154', 'Torroja del Priorat', 'Priorat', 'Tarragona'),
  ('43155', 'Tortosa', 'Baix Ebre', 'Tarragona'),
  ('43156', 'Ulldecona', 'Montsià', 'Tarragona'),
  ('43157', 'Ulldemolins', 'Priorat', 'Tarragona'),
  ('43158', 'Vallclara', 'Conca de Barberà', 'Tarragona'),
  ('43159', 'Vallfogona de Riucorb', 'Conca de Barberà', 'Tarragona'),
  ('43160', 'Vallmoll', 'Alt Camp', 'Tarragona'),
  ('43161', 'Valls', 'Alt Camp', 'Tarragona'),
  ('43162', 'Vandellòs i l''Hospitalet de l''Infant', 'Baix Camp', 'Tarragona'),
  ('43163', 'Vendrell, el', 'Baix Penedès', 'Tarragona'),
  ('43164', 'Vespella de Gaià', 'Tarragonès', 'Tarragona'),
  ('43165', 'Vilabella', 'Alt Camp', 'Tarragona'),
  ('43166', 'Vilallonga del Camp', 'Tarragonès', 'Tarragona'),
  ('43167', 'Vilanova d''Escornalbou', 'Baix Camp', 'Tarragona'),
  ('43168', 'Vilanova de Prades', 'Conca de Barberà', 'Tarragona'),
  ('43169', 'Vilaplana', 'Baix Camp', 'Tarragona'),
  ('43170', 'Vila-rodona', 'Alt Camp', 'Tarragona'),
  ('43171', 'Vila-seca', 'Tarragonès', 'Tarragona'),
  ('43172', 'Vilaverd', 'Conca de Barberà', 'Tarragona'),
  ('43173', 'Vilella Alta, la', 'Priorat', 'Tarragona'),
  ('43174', 'Vilella Baixa, la', 'Priorat', 'Tarragona'),
  ('43175', 'Vilalba dels Arcs', 'Terra Alta', 'Tarragona'),
  ('43176', 'Vimbodí i Poblet', 'Conca de Barberà', 'Tarragona'),
  ('43177', 'Vinebre', 'Ribera d''Ebre', 'Tarragona'),
  ('43178', 'Vinyols i els Arcs', 'Baix Camp', 'Tarragona'),
  ('43901', 'Deltebre', 'Baix Ebre', 'Tarragona'),
  ('43902', 'Sant Jaume d''Enveja', 'Montsià', 'Tarragona'),
  ('43903', 'Camarles', 'Baix Ebre', 'Tarragona'),
  ('43904', 'Aldea, l''', 'Baix Ebre', 'Tarragona'),
  ('43905', 'Salou', 'Tarragonès', 'Tarragona'),
  ('43906', 'Ampolla, l''', 'Baix Ebre', 'Tarragona'),
  ('43907', 'Canonja, la', 'Tarragonès', 'Tarragona')
on conflict (codi_ine) do update
  set nom = excluded.nom, comarca = excluded.comarca, provincia = excluded.provincia;

-- ---------------------------------------------------------------------------
-- 4. Las dos capas: GRANT + RLS
-- ---------------------------------------------------------------------------
-- Catálogo público sin datos personales, como `productos` y `causas` (20260730095000):
-- lo lee cualquier cuenta con sesión, porque lo necesita el desplegable del alta de
-- oferta y el de la ficha de ubicación. Escritura: ninguna. Se actualiza por migración,
-- que es como se actualiza un nomenclátor oficial.
grant select on municipios to authenticated;

alter table municipios enable row level security;

drop policy if exists "municipis: qualsevol autenticat" on municipios;
create policy "municipis: qualsevol autenticat"
  on municipios for select to authenticated
  using (true);

-- Verificación:
--   select count(*) from municipios;                                    -- 947
--   select count(distinct comarca) from municipios;                     -- 43
--   select provincia, count(*) from municipios group by 1 order by 1;
--   select nom, comarca from municipios where codi_ine = '08019';       -- Barcelona / Barcelonès
--   select has_table_privilege('authenticated','public.municipios','SELECT');  -- t
